/**
 * Copyright (c) 2025 OpenShort.link Contributors
 * Licensed under the GNU Affero General Public License Version 3 (AGPL-3.0)
 */
export const LOGO_DATA_URI = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIiB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiI+CjxwYXRoIGZpbGw9IiNGQUJCMDUiIGQ9Ik01MTEuOTggMjUyLjk0IEEyNTYgMjU2IDAgMSAwIDQ4MC41MiAzNzguOTggQTI1NyAyNTcgMCAwIDEgMjI4LjA3IDI4NS45OCBBNDIzIDQyMyAwIDAgMCA1MTEuOTggMjUyLjk0WiIvPgo8Y2lyY2xlIGN4PSIyODEiIGN5PSIxNDEiIHI9IjQ5IiBmaWxsPSIjRUE0QTNCIi8+Cjwvc3ZnPg==";
